Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineShop.Data;
using OnlineShop.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ProductController : Controller
    {
        ApplicationDbContext _db;

        // get root directory wwwroot
        IHostingEnvironment _dir;
       
       public ProductController(ApplicationDbContext db, IHostingEnvironment dir)
        {
            _db = db;
            _dir = dir
 ;        }
        public IActionResult Index()
        {
            // Realtionship data ... buind and join
            // Another table data buind by Froign key .. Primary key ... 
            // how see Include( Lamda expression )   productTypes and SpecialTag table data join and buind
            
            var products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).ToList(); 
            
            return View(products);
        }

        // min and max Range product ... find 
        // post 
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Index(decimal lowAmount, decimal largeAmount)
        {
            var products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();

            return View(products);
        } 

        // *************** Create ********************
        // get create action 
        public IActionResult Create()
        {
            // For dorpdown menu we want to add                                  value   dispalay
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.SpecialTag.ToList(), "Id", "TagName");

            return View();
        }

        // post create action 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile image)
        {
           
            if (ModelState.IsValid)
            {
                var searchProduct = _db.Products.FirstOrDefault(c => c.Name == product.Name);

                if(searchProduct != null)
                {
                    ViewBag.message = "This product is already exist";

                    ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
                    ViewData["TagId"] = new SelectList(_db.SpecialTag.ToList(), "Id", "TagName");
                    
                    return View();
                }
                    
                    // save image into local directory 
                if (image != null)
                {
                    var name = Path.Combine(_dir.WebRootPath + "/images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));

                    product.Image = "images/" + image.FileName;  // with path .. file name store into database only 

                }

                // defalut image set
                if(image == null)
                {
                    product.Image = "images/10.png";
                }
          
                _db.Products.Add(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.SpecialTag.ToList(), "Id", "TagName");
            return View(product);
        }

        // ************ Edit *******************
        // get Edit Action Method 
        public IActionResult Edit(int? id)
        {

            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.SpecialTag.ToList(), "Id", "TagName");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).FirstOrDefault(c => c.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // post Edit Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product product, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                // save image into local directory 
                if (image != null)
                {
                    var name = Path.Combine(_dir.WebRootPath + "/images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));

                    product.Image = "images/" + image.FileName;  // with path .. file name store into database only 

                }

                // defalut image set
                if (image == null)
                {
                    product.Image = "images/10.png";
                }

                _db.Products.Update(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.SpecialTag.ToList(), "Id", "TagName");
            return View(product);
        }

        // ************** Details ********************
        // get Details page 

        public IActionResult Details(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).FirstOrDefault(c => c.Id == id);
            if(product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // post Details page

        // ******************* Delete ********************
        // get delete action method 

        public IActionResult Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).Where(c => c.Id == id).FirstOrDefault();

            if(product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // post delete action method
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var product = _db.Products.FirstOrDefault(c => c.Id == id);
            if(product == null)
            {
                return NotFound();
            }
            _db.Products.Remove(product);
            await _db.SaveChangesAsync();  
            return RedirectToAction(nameof(Index));
        }

    }
}

Areas/Admin/Controllers/SpecialTagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Data;
using OnlineShop.Models;

namespace OnlineShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SpecialTagController : Controller
    {
        ApplicationDbContext _db;

        public SpecialTagController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            Console.WriteLine("Hi Mehedi");
            var data = _db.SpecialTag.ToList();
            return View(data);
        }

        // get the Create action 
        public IActionResult Create()
        {
            return View();
        }

        // post the Create data .. action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTag specialTag)
        {
            if(ModelState.IsValid)
            {
                _db.SpecialTag.Add(specialTag);
               await _db.SaveChangesAsync();
              return RedirectToAction(nameof(Index));

            }

            return View(specialTag);

        }

        // *********** Edit ************
        // get action for Edit
        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var data = _db.SpecialTag.Find(id);
            if(data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        // post action for Edit 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SpecialTag specialTag)
        {
            if(ModelState.IsValid)
            {
                _db.SpecialTag.Update(specialTag);
               await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            return View(specialTag);
        }

        // *************** Details **************8
        // Get action for Details
        public IActionResult Details(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var data = _db.SpecialTag.Find(id);
            if(data == null)
            {
                return NotFound();
            }

            return View(data);
        }
        // post action for Details 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details()
        {
            return RedirectToAction(nameof(Index));
        }

        // **************** Delete **************
        // Get action for Delete
        public IActionResult Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var data = _db.SpecialTag.Find(id);
            if(data == null)
            {
                return NotFound();
            }

            return View(data);
        }

        // post action for Delete 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, SpecialTag specialTag)
        {
            if(id == null)
            {
                return NotFound();
            }
            if(id != specialTag.Id)
            {
                return NotFound();
            }

            // this data present into database or not check
            var data = _db.SpecialTag.Find(id);
            if(data == null)
            {
                return NotFound();
            }

            if(ModelState.IsValid)
            {                       
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(specialTag);

        }

    }
}

Views/Shared/_ButtonPartial.cshtml
@model string[]
@{
}
 
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="@Model[0]" class="btn btn-primary" asp-route-id="@Model[1]">Edit</a>
        <a asp-action="Details" asp-controller="@Model[0]" class="btn btn-success" asp-route-id="@Model[1]">Details</a>
        <a asp-action="Delete" asp-controller="@Model[0]" class="btn btn-danger " asp-route-id="@Model[1]">Delete</a>
    </div>
</td>

Views/Shared/_Layout.cshtml
@using OnlineShop.Utiliy
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor 
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");

    int count = 0;
    List<Product> products = HttpContextAccessor.HttpContext.Session.Get<List<Product>>("products");
    if(products == null)
    {
        products = new List<Product>();
    }
    count = products.Count();
    Console.WriteLine(count);

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(userRole == "Super user")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductType" asp-action="Index">ProductType</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">Special Tag</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                        }
                        else{
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">Cart (@count)</a>
                            </li>
                        }
                      
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnlineShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>